<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-ios</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <IsBindingProject>true</IsBindingProject>
    <NoBindingEmbedding>true</NoBindingEmbedding>
  </PropertyGroup>

  <ItemGroup>
    <ObjcBindingApiDefinition Include="XamarinApiDef\ApiDefinitions.cs" />
    <ObjcBindingCoreSource Include="XamarinApiDef\StructsAndEnums.cs" />
  </ItemGroup>
  <ItemGroup>
    <NativeReference Include="tealium-xcframeworks\TealiumSwift.xcframework">
      <Kind>Framework</Kind>
      <SmartLink>True</SmartLink>
    </NativeReference>
    <NativeReference Include="tealium-xcframeworks\TealiumWrapperCocoapods.xcframework">
      <Kind>Framework</Kind>
      <SmartLink>True</SmartLink>
      <Frameworks>TealiumSwift</Frameworks>
    </NativeReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="XamarinApiDef\StructsAndEnums.cs" />
    <Compile Remove="XamarinApiDef\ApiDefinitions.cs" />
  </ItemGroup>
</Project>
